// <auto-generated />
using System;
using Exsm3944_MySqlAuthentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exsm3944_MySqlAuthentication.Migrations.Vehicle
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20230406223212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer_email")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CustomerEmail"), "utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");
                });

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("colour")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Colour"), "utf8mb4");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer_email")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CustomerEmail"), "utf8mb4");

                    b.Property<int>("ModelID")
                        .HasColumnType("int(10)")
                        .HasColumnName("model_id");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int(4)")
                        .HasColumnName("model_year");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("vin")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("VIN"), "utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("ModelID")
                        .HasDatabaseName("FK_Vehicle_VehicleModel");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.VehicleModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer_email")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CustomerEmail"), "utf8mb4");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("int(10)")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasDatabaseName("FK_VehicleModel_Manufacturer");

                    b.ToTable("vehicle_model");
                });

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.Vehicle", b =>
                {
                    b.HasOne("Exsm3944_MySqlAuthentication.Models.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_VehicleModel");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.VehicleModel", b =>
                {
                    b.HasOne("Exsm3944_MySqlAuthentication.Models.Manufacturer", "Manufacturer")
                        .WithMany("VehicleModels")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VehicleModel_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.Manufacturer", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Models.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
