// <auto-generated />
using System;
using Exsm3944_MySqlAuthentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exsm3944_MySqlAuthentication.Migrations.Vehicle
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20230327022027_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Exsm3944_MySqlAuthentication.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("colour")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Colour"), "utf8mb4");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer_email")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CustomerEmail"), "utf8mb4");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("manufacturer")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Manufacturer"), "utf8mb4");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("model")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Model"), "utf8mb4");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int(4)")
                        .HasColumnName("model_year");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("vin")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("VIN"), "utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
